"""empty message

Revision ID: d31c4a5c15c3
Revises: 
Create Date: 2020-05-08 13:08:32.995843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31c4a5c15c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_chat_demo_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('online_class_id', sa.Integer(), nullable=False),
    sa.Column('banned_user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('baned_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_demo_classe_stream_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_class_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_name', sa.String(length=150), nullable=True),
    sa.Column('cano_url', sa.String(length=250), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True, comment='amount or percentage'),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('coupon_valid_start_date', sa.Date(), nullable=False),
    sa.Column('coupon_valid_end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('demo_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('online_class_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_name')
    )
    op.create_table('student_select_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=65), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_titile', sa.String(length=150), nullable=False),
    sa.Column('privileges', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_titile')
    )
    op.create_table('courses_mapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pac_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=False),
    sa.Column('cano_url', sa.String(length=250), nullable=False),
    sa.Column('cover_banner', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expire_month', sa.Integer(), nullable=False),
    sa.Column('expire_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['expire_month'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.BigInteger(), nullable=False),
    sa.Column('parent_mobile', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('ic_number', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('online_register', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('forget_password_key', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('users_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('used_for', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('online_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('class_title', sa.String(length=200), nullable=False),
    sa.Column('canonical_url', sa.String(length=350), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('online_demo_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('class_title', sa.String(length=200), nullable=False),
    sa.Column('canonical_url', sa.String(length=350), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_banner', sa.String(length=150), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('is_start', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('pac_compulsory_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pac_course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pac_course_id'], ['pac_course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pac_optional_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pac_course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pac_course_id'], ['pac_course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_package_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('coupon_code', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('total_payable_amount', sa.Float(), nullable=False),
    sa.Column('transcation_id', sa.String(length=450), nullable=True),
    sa.Column('receipt', sa.String(length=250), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True, comment='online, offline'),
    sa.Column('subs_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_code'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['pac_course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_subscribe_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ic_number', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('is_upgraded', sa.Boolean(), nullable=True),
    sa.Column('course_assign_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_trans_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('coupon_code', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('total_payable_amount', sa.Float(), nullable=False),
    sa.Column('transcation_id', sa.String(length=450), nullable=True),
    sa.Column('receipt', sa.String(length=250), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True, comment='online, offline'),
    sa.Column('purpose', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['coupon_code'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['pac_course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_assing_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=150), nullable=True),
    sa.Column('devices', sa.String(length=250), nullable=True),
    sa.Column('login_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ban_chat_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('online_class_id', sa.Integer(), nullable=False),
    sa.Column('banned_user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('baned_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['banned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['online_class_id'], ['online_classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_classe_stream_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_class_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['live_class_id'], ['online_classes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('online_class_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=155), nullable=True),
    sa.ForeignKeyConstraint(['online_class_id'], ['online_classes.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_student_attendence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topices_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users_demo.id'], ),
    sa.ForeignKeyConstraint(['topices_id'], ['online_demo_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attendence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topices_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_join', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topices_id'], ['online_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_subs_pac_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_pac_subs_id', sa.Integer(), nullable=True),
    sa.Column('subs_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stu_pac_subs_id'], ['student_package_subscription.id'], ),
    sa.ForeignKeyConstraint(['subs_month'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_subs_pac_optional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_pac_subs_id', sa.Integer(), nullable=True),
    sa.Column('optional_subs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['optional_subs'], ['pac_optional_subjects.id'], ),
    sa.ForeignKeyConstraint(['stu_pac_subs_id'], ['student_package_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subs_pac_optional')
    op.drop_table('student_subs_pac_months')
    op.drop_table('student_attendence')
    op.drop_table('demo_student_attendence')
    op.drop_table('chat')
    op.drop_table('broadcast_classe_stream_records')
    op.drop_table('ban_chat_users')
    op.drop_table('user_session_log')
    op.drop_table('teacher_assing_course')
    op.drop_table('subscription_trans_log')
    op.drop_table('student_subscribe_courses')
    op.drop_table('student_package_subscription')
    op.drop_table('school_details')
    op.drop_table('pac_optional_subjects')
    op.drop_table('pac_compulsory_subjects')
    op.drop_table('online_demo_classes')
    op.drop_table('online_classes')
    op.drop_table('users_demo')
    op.drop_table('users')
    op.drop_table('pac_course')
    op.drop_table('courses_mapper')
    op.drop_table('user_roles')
    op.drop_table('subjects')
    op.drop_table('student_select_course')
    op.drop_table('months')
    op.drop_table('demo_chat')
    op.drop_table('courses')
    op.drop_table('coupon')
    op.drop_table('contact_us')
    op.drop_table('broadcast_demo_classe_stream_records')
    op.drop_table('ban_chat_demo_users')
    # ### end Alembic commands ###
