"""empty message

Revision ID: da9293188d16
Revises: d31c4a5c15c3
Create Date: 2020-05-11 13:37:41.110233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da9293188d16'
down_revision = 'd31c4a5c15c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seminars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('canonical_url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('seminar_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seminar_attend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminars.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seminar_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('topic_titile', sa.String(length=250), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminars.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ban_chat_demo_users', 'banned_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ban_chat_demo_users', 'online_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ban_chat_demo_users', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('broadcast_demo_classe_stream_records', 'stream_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('demo_chat', 'online_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('demo_chat', 'receiver_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('demo_chat', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('demo_chat', 'user_id',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.create_unique_constraint(None, 'months', ['month_name'])
    op.alter_column('online_demo_classes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='When teacher start the class and came online it will true',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('fk_pac_course_cou_id', 'pac_course', type_='foreignkey')
    op.create_foreign_key(None, 'pac_course', 'months', ['expire_month'], ['id'])
    op.create_foreign_key(None, 'pac_course', 'courses', ['course_id'], ['id'])
    op.drop_column('pac_course', 'expire_date')
    op.drop_constraint('fk_pac_opt_pac_subject_id', 'pac_optional_subjects', type_='foreignkey')
    op.drop_constraint('fk_pac_opt_pac_cour_id', 'pac_optional_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'pac_optional_subjects', 'pac_course', ['pac_course_id'], ['id'])
    op.create_foreign_key(None, 'pac_optional_subjects', 'subjects', ['subject_id'], ['id'])
    op.alter_column('school_details', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('shcool_details_FK', 'school_details', type_='foreignkey')
    op.create_foreign_key(None, 'school_details', 'users', ['student_id'], ['id'])
    op.alter_column('student_package_subscription', 'receipt',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_constraint('student_subs_pac_months_FK', 'student_subs_pac_months', type_='foreignkey')
    op.drop_constraint('student_subs_pac_months_FK_1', 'student_subs_pac_months', type_='foreignkey')
    op.create_foreign_key(None, 'student_subs_pac_months', 'months', ['subs_month'], ['id'])
    op.create_foreign_key(None, 'student_subs_pac_months', 'student_package_subscription', ['stu_pac_subs_id'], ['id'])
    op.drop_constraint('student_subs_pac_optional_FK', 'student_subs_pac_optional', type_='foreignkey')
    op.create_foreign_key(None, 'student_subs_pac_optional', 'student_package_subscription', ['stu_pac_subs_id'], ['id'])
    op.create_foreign_key(None, 'student_subs_pac_optional', 'pac_optional_subjects', ['optional_subs'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_subs_pac_optional', type_='foreignkey')
    op.drop_constraint(None, 'student_subs_pac_optional', type_='foreignkey')
    op.create_foreign_key('student_subs_pac_optional_FK', 'student_subs_pac_optional', 'student_package_subscription', ['stu_pac_subs_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'student_subs_pac_months', type_='foreignkey')
    op.drop_constraint(None, 'student_subs_pac_months', type_='foreignkey')
    op.create_foreign_key('student_subs_pac_months_FK_1', 'student_subs_pac_months', 'months', ['subs_month'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('student_subs_pac_months_FK', 'student_subs_pac_months', 'student_package_subscription', ['stu_pac_subs_id'], ['id'], onupdate='CASCADE')
    op.alter_column('student_package_subscription', 'receipt',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_constraint(None, 'school_details', type_='foreignkey')
    op.create_foreign_key('shcool_details_FK', 'school_details', 'users', ['student_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('school_details', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'pac_optional_subjects', type_='foreignkey')
    op.drop_constraint(None, 'pac_optional_subjects', type_='foreignkey')
    op.create_foreign_key('fk_pac_opt_pac_cour_id', 'pac_optional_subjects', 'pac_course', ['pac_course_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_pac_opt_pac_subject_id', 'pac_optional_subjects', 'subjects', ['subject_id'], ['id'], onupdate='CASCADE')
    op.add_column('pac_course', sa.Column('expire_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'pac_course', type_='foreignkey')
    op.drop_constraint(None, 'pac_course', type_='foreignkey')
    op.create_foreign_key('fk_pac_course_cou_id', 'pac_course', 'courses', ['course_id'], ['id'], onupdate='CASCADE')
    op.alter_column('online_demo_classes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               comment='When teacher start the class and came online it will true',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'months', type_='unique')
    op.alter_column('demo_chat', 'user_id',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('demo_chat', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('demo_chat', 'receiver_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('demo_chat', 'online_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('broadcast_demo_classe_stream_records', 'stream_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('ban_chat_demo_users', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ban_chat_demo_users', 'online_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ban_chat_demo_users', 'banned_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('seminar_details')
    op.drop_table('seminar_attend')
    op.drop_table('seminars')
    # ### end Alembic commands ###
